export default function ProductDetails() {
  return (
    <>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
      <div>ProductDetails</div>
    </>
  );
}
